# general settings
name: EDVR_L_x16_SR_IMG_0028_woTSA
model_type: EDVRModel
scale: 16
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: IMG_0028
    type: SingleVideoDataset
    dataroot: datasets/adobe240f
    dataroot_flow: ~
    # meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    # val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disc

    num_frame: 21
    # gt_size: 256
    # interval_list: [1]
    # random_reverse: false
    # use_flip: true
    # use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

# network structures
network_g:
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 128
  num_frame: 21
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: false
  scale: 16

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  # resume_state: experiments/EDVR_L_x16_SR_vimeo90k_woTSA_600k_B4G8_valREDS4_wandb/training_states/575000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 150000, 150000]
    restart_weights: [1, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 30000
  warmup_iter: -1  # no warm up
  dcn_lr_mul: 1

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum

# validation settings
# val:
#   val_freq: !!float 5e3
#   save_img: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
